version: '2'
services:
    server:
      build: .
      restart: always
      ports:
        - "8000:8000"
      volumes:
        - ./config:/config
      environment:
        - DB_HOST=database
        - DB_PORT=5432
        - HTTP_PORT=8000
        - GIN_MODE=release